server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: toyProject

  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: als1063113!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10       # ?? ??? ??
      minimum-idle: 5            # ?? ?? ???
      idle-timeout: 30000        # idle ??? ?? ?? (ms)
      connection-timeout: 30000  # ??? ??? ??? ??? ? ?? ?? (ms)
      pool-name: MyHikariCP

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none    # ??: update / create, ??: validate / none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  profiles:
    active: dev   # ?? ?? ????

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG           # SQL ?? ??
    org.hibernate.type.descriptor.sql: TRACE  # ???? ???? ???? ??
